### ISSUE TITLE
Download ISM data from Globus

### ISSUE THREAD

**Issue by headmetal** [ACCESS-NRI/access-ism-data-pool#3]
Download the following ISM datasets from Globus to temporary home on kj13:

ISMIP6 23rd Century Projections - [endpoint](https://app.globus.org/file-manager?origin_id=3881e705-3290-4e81-8990-0ef8cfb54d74)
ISMIP6 23rd Century Forcing Datasets - [endpoint](https://app.globus.org/file-manager?origin_id=fdceb97d-9e6c-44c0-8fb2-433a609b0878)
ISMIP6 initMIP-Antarctica simulations - [endpoint](https://app.globus.org/file-manager?origin_id=daacf9a3-825f-4cf9-ad2c-11604b160529)
ISMIP6 ABUMIP Simulations - [endpoint](https://app.globus.org/file-manager?origin_id=5b716915-ce19-45f7-95e5-2d2b11bc2946)
ISMIP6 21st Century Antarctic Projections - [endpoint](https://app.globus.org/file-manager?origin_id=09cb49bb-12fd-44af-a0aa-11b31f31d3a5)
ISMIP6 21st Century Greenland Projections - [endpoint](https://app.globus.org/file-manager?origin_id=56c9948c-ec53-4d7e-8d32-9f78b7de66c5)
ISMIP6 21st Century Forcing Datasets - [endpoint](https://app.globus.org/file-manager?origin_id=ad1a6ed8-4de0-4490-93a9-8258931766c7)
ISMIP6 initMIP-Greenland simulations - [endpoint](https://app.globus.org/file-manager?origin_id=9d27971e-13a6-4c6d-8d13-3d2ba72a56e5)

**Comment by rbeucher** [comment]
- [ ] ISMIP6 23rd Century Projections - [endpoint](https://app.globus.org/file-manager?origin_id=3881e705-3290-4e81-8990-0ef8cfb54d74)
- [ ] IISMIP6 23rd Century Forcing Datasets - [endpoint](https://app.globus.org/file-manager?origin_id=fdceb97d-9e6c-44c0-8fb2-433a609b0878)
- [ ] IISMIP6 initMIP-Antarctica simulations - [endpoint](https://app.globus.org/file-manager?origin_id=daacf9a3-825f-4cf9-ad2c-11604b160529)
- [ ] IISMIP6 ABUMIP Simulations - [endpoint](https://app.globus.org/file-manager?origin_id=5b716915-ce19-45f7-95e5-2d2b11bc2946)
- [ ] IISMIP6 21st Century Antarctic Projections - [endpoint](https://app.globus.org/file-manager?origin_id=09cb49bb-12fd-44af-a0aa-11b31f31d3a5)
- [ ] IISMIP6 21st Century Greenland Projections - [endpoint](https://app.globus.org/file-manager?origin_id=56c9948c-ec53-4d7e-8d32-9f78b7de66c5)
- [ ] IISMIP6 21st Century Forcing Datasets - [endpoint](https://app.globus.org/file-manager?origin_id=ad1a6ed8-4de0-4490-93a9-8258931766c7)
- [ ] IISMIP6 initMIP-Greenland simulations - [endpoint](https://app.globus.org/file-manager?origin_id=9d27971e-13a6-4c6d-8d13-3d2ba72a56e5)

**Comment by rbeucher** [comment]
All completed.

Total is 12TB.

R
